version: '3.4'

services:
  sourcingdb:
    image: mongo

  esourcing.product:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
        context: .
        dockerfile: ESourcingProducts/Dockerfile

  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
      context: .
      dockerfile: ESourcingSourcing/Dockerfile

 

