version: '3.4'

services:
  sourcingdb:
    image: mongo

  esourcingproducts:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: ESourcingProducts/Dockerfile

  esourcingsourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
      context: .
      dockerfile: ESourcingSourcing/Dockerfile

